brushandlens/accounts/urls.py
from django.urls import path

from .views import (
    LogInView, SignUpView, LogOutView, ChangeProfileView, ChangePasswordView,
)

app_name = 'accounts'

urlpatterns = [
    path('log-in/', LogInView.as_view(), name='log_in'),
    path('log-out/', LogOutView.as_view(), name='log_out'),
    path('sign-up/', SignUpView.as_view(), name='sign_up'),

    path('change/profile/', ChangeProfileView.as_view(), name='change_profile'),
    path('change/password/', ChangePasswordView.as_view(), name='change_password'),
]

brushandlens/brushandlens/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('root.urls')),
    path('admin/', admin.site.urls),
]

brushandlens/root/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('about/', views.about, name='about'),
    path('preview/', views.preview, name="preview"),
    path('feelinglucky/', views.feelinglucky, name="feelinglucky"),
    path('gallery/', views.gallery, name='gallery'),
    path('artistworks/', views.artistworks, name='artistworks'),
    path('api/get_artists', views.get_artists, name='get_artists'),
    path('accounts/', include('accounts.urls')),
]

brushandlens/root/models.py
from django.db import models
from django.utils import timezone

from django.contrib.auth.models import User

class Artist(models.Model):
    name = models.CharField(max_length=256)
    description = models.TextField()
    type = models.TextField()

class Images(models.Model):
    title = models.CharField(max_length=256)
    image_path = models.CharField(max_length=260)
    price = models.IntegerField()
    date_posted = models.DateTimeField(default=timezone.now)
    artist = models.ForeignKey(Artist, on_delete=models.CASCADE)

class Likes(models.Model):
    image_path = models.CharField(max_length=260)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

brushandlens/root/views.py
from django.shortcuts import render
from django.template import loader
from django.http import JsonResponse
from .models import Artist
from .models import Images

import random

def index(request):
    context = {'active': 'Home'}
    artist = Artist.objects.get(id=1)
    image = Images.objects.filter(artist=artist).get(pk=12)
    context = {
               'active' : 'Home',
               'artist': artist,
               'image' : image
                }
    return render(request, 'root/index.html', context)

def about(request):
    context = {'active': 'About'}
    return render(request, 'root/about.html', context)

def feelinglucky(request):
    images = Images.objects.all()
    image_data = []
    for image in images:
        image_data.append({
            'image_label': image.title,
            'image_src': image.image_path,
            'image_desc':image.artist.description,
            'image_pr': image.price
        })
    
    context = {'active': 'Lucky',
                'slider_info':[
                {
                'image_src': "../static/root/images/bg-masthead.jpg",
                'image_label': "Image 1",
                'image_desc': "Some representative placeholder content for the first slide.",
                'image_pr': '35'
                },
                {
                'image_src': "../static/root/images/bg-masthead.jpg",
                'image_label': "Image 2",
                'image_desc': "Some representative placeholder content for the second slide.",
                'image_pr': '25'
                },
                {
                'image_src': "../static/root/images/bg-masthead.jpg",
                'image_label': "Image 3",
                'image_desc': "Some representative placeholder content for the third slide.",
                'image_pr': '45'
                }
                ]
              }

    context = {'active': 'Lucky',
               'slider_info': list(image_data)}
    return render(request, 'root/preview.html', context)

def preview(request):
    image_list = []
    if(request.GET.get('id')):
        artist = Artist.objects.get(id=(int(request.GET.get('id'))))
    elif(request.GET.get('img_id')):
        first_image = Images.objects.filter(pk = int(request.GET.get('img_id')))
        artist = first_image[0].artist
        image_dict = {
            'image_label': first_image[0].title,
            'image_src': first_image[0].image_path,
            'image_desc': first_image[0].artist.description,
            'image_pr': first_image[0].price
        }
        
        image_list.append(image_dict)
    #artist = Artist.objects.get(id=(int(request.GET.get('id'))))
    # Retrieve all images associated with the artist
    images = Images.objects.filter(artist=artist)

    # Create a list of image dictionaries to pass to JsonResponse
    for image in images:
        
        if (request.GET.get('img_id')):
            if (image.pk == int(request.GET.get('img_id'))):
                continue
            
        image_dict = {
            'image_label': image.title,
            'image_src': image.image_path,
            'image_desc':image.artist.description,
            'image_pr': image.price
        }
        image_list.append(image_dict)
        
    context = {'active': 'Lucky',
               'slider_info': list(image_list)}
    
    return render(request, 'root/preview.html', context)

def gallery(request):
    context = {'active': 'Gallery'}
    return render(request, 'root/gallery.html', context)

def artistworks(request):
    art = Artist.objects.all()
    imgs = Images.objects.filter(artist = art[int(request.GET.get('id')) - 1])
    theme_choices = ["popularity", "price"]
    for img in imgs:
        img.theme = random.choice(theme_choices)
    context = {
                'active': 'Artist',
                'artists': art[int(request.GET.get('id')) - 1],
                'images': imgs
               }
    return render(request, 'root/artistworks.html', context)

def get_artists(request):
    artists = Artist.objects.all()
    artist_data = []
    for artist in artists:
        imges = Images.objects.filter(artist=artist)
        first_image = imges.first()
        data = {
            'id': artist.id,
            'name': artist.name,
            'description': artist.description,
            'type': artist.type,
            'image_path': first_image.image_path if first_image else None,
            'price': first_image.price if first_image else None,
            'date_posted': first_image.date_posted if first_image else None,
            'posts' : imges.count(),
            'likes' : imges.count() * random.randrange(44, 46)
        }
        artist_data.append(data)
    
    return JsonResponse({'goats': list(artist_data)})
    return JsonResponse( {
        'goats' :[{
            'uid': '1',
            'name': 'Artist1',
            'theme': 'design',
            'image': 'bg-masthead.jpg'   
        }
        ,
        {
            'uid': '2',
            'name': 'Artist2',
            'theme': 'market',
            'image': 'bg-masthead.jpg'   
        },
        {
            'uid': '3',
            'name': 'Artist3',
            'theme': 'develop',
            'image': 'bg-masthead.jpg'   
        },
        {
            'uid': '4',
            'name': 'Artist4',
            'theme': 'market',
            'image': 'bg-masthead.jpg' 
        },
        {
            'uid': '5',
            'name': 'Artist5',
            'theme': 'br',
            'image': 'bg-masthead.jpg'  
        },
        {
            'uid': '6',
            'name': 'Artist6',
            'theme': 'br',
            'image': 'bg-masthead.jpg'
        }]})

brushandlens/root/templates/root/about.html
{% extends "root/base.html" %}
{% block content %}
<div class="container" style="width:100%">
    <div class="row mt-5 py-5">
      <div class="col-lg-6">
        <img class="w-100" src="../static/root/images/45322.jpg" />
      </div>
      <div class="col-lg-6">
        <div class="p-5 mt-4" style="border-left: 2px solid black;">
            <h1 class="display-4">About Us</h1>
            <p class="lead px-0">Welcome to Brush & Lens! 📸 Discover captivating images, explore talented photographers, and find the perfect photo to bring your project to life. Dive in and let your creativity soar</p>
            <a href="{% url 'feelinglucky' %}" class="btn btn-outline-dark">Look Around</a>
          </div>
      </div>
  </div>
  </div>
{% endblock content %}

brushandlens/root/templates/root/artistworks.html
{% extends "root/base.html" %}


{% block header %}
  <link href="https://fonts.googleapis.com/css?family=https://fonts.googleapis.com/css?family=Inconsolata:400,500,600,700|Raleway:400,400i,500,500i,600,600i,700,700i" rel="stylesheet">
  {% load static %}
  <link href="{% static 'root/css/aos.css' %}" rel="stylesheet" />
  <link href="{% static 'root/css/swiper-bundle.min.css' %}" rel="stylesheet" />
   
{% endblock %}
{% block content %}
<section>
  <main id="main">

    <!-- ======= Works Section ======= -->
    <section class="section site-portfolio">
      <div class="container">
        <div class="row mb-5 align-items-center">
          <div class="col-md-12 col-lg-6 mb-4 mb-lg-0 justify-content-evenly" data-aos="fade-up">
            <div class="row justify-content-bottom">
            <div class="artist-thumbnail col-md-12 col-lg-3">
              <img src="../static/root/images/Person looking in binoculars-01.svg">  
            </div>
            <div class="col-md-12 col-lg-6 justify-content-center">
              <h2 class="mt-5">{{ artists.name }}</h2>
              <p class="mb-0 ms-0 px-0">{{artists.description}}</p>
            </div>
            </div>
          </div>
          <div class="col-md-12 col-lg-6 text-start text-lg-end" data-aos="fade-up" data-aos-delay="100">
            <div id="filters" class="filters">
              <p>Sort By: </p>
              <a href="#" data-filter="*" class="active">Date</a>
              <a href="#" data-filter=".popularity">Popularity</a>
              <a href="#" data-filter=".price">Price</a>
            </div>
          </div>
        </div>
        <div id="portfolio-grid" class="row no-gutter" data-aos="fade-up" data-aos-delay="0">
          {% for image in images %}
            <div class="item {{image.theme}} col-sm-6 col-md-4 col-lg-4 mb-4">
              
              <a href="/preview?img_id={{image.pk}}" class="item-wrap fancybox">
                <div class="work-info">
                  <span>Buy Now ${{image.price}}</span>
                </div>
                <img class="img-fluid" src="../static/root{{image.image_path}}">
              </a>
            </div>
          {% endfor %}
        </div>
      </div>
    </section><!-- End  Works Section -->

  </main><!-- End #main -->
  <!-- Vendor JS Files -->
  <script src="{% static 'root/js/isotope.pkgd.min.js' %}"></script>
  <script src="{% static 'root/js/aos.js' %}"></script>
  <script src="{% static 'root/js/swiper-bundle.min.js' %}"></script>
  <!-- Template Main JS File -->
  <script src="{% static 'root/js/art-work.js' %}">
  </script>

</section>
{% endblock content %}

brushandlens/root/templates/root/base.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Brush and Lens</title>
        <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
        <!-- Font Awesome icons (free version)-->
        <script src="https://use.fontawesome.com/releases/v6.1.0/js/all.js" crossorigin="anonymous"></script>
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Varela+Round" rel="stylesheet" />
        <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet" />
          <!-- Template Main CSS File -->
        <link href="{% static 'root/css/art_works.css' %}" rel="stylesheet">
        <link href="{% static 'root/css/styles.css' %}" rel="stylesheet" />
        <script src="/static/root/lib/jquery/jquery.min.js"></script>
        <script src="/static/root/js/account-view.js"></script>

    <!-- Required Bootstrap Icons CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.2/font/bootstrap-icons.css"
          integrity="sha384-b6lVK+yci+bfDmaY1u0zE8YYJt0TZxLEAFyYSLHId4xoVvsrQu3INevFKo+Xir8e" crossorigin="anonymous">
    {% block header %}{% endblock %}
</head>
    <body id="page-top"> {# make the "sticky footer" #}
        <!-- navbar -->
        <nav class="navbar navbar-expand-lg navbar-light fixed-top navbar-shrink" id="mainNav">
            <div class="container px-4 px-lg-5">
                <a class="navbar-brand" href="/">Brush &#38; Lens</a>
                <button class="navbar-toggler navbar-toggler-right" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                    Menu
                    <i class="fas fa-bars"></i>
                </button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav ms-auto">
                        {% if active != 'Home' %}
                            <li class="nav-item"><a class="nav-link" href="{% url 'index' %}">Home</a></li>
                        {% endif %}
                        <li class="nav-item"><a class="nav-link {% if active == 'Gallery' %} active{% endif %}" href="{% url 'gallery' %}">Gallery</a></li>
                        <li class="nav-item"><a class="nav-link {% if active == 'Lucky' %} active{% endif %}" href="{% url 'feelinglucky' %}">Explore!</a></li>
                        <li class="nav-item"><a class="nav-link {% if active == 'About' %}active{% endif %}" href="{% url 'about' %}">About</a></li> <!--remove this>-->
                        <li class="nav-item" id="nav-item-account">
                            <div class="dropdown">
                                <button class="shadow-none border-start-0 border-end-0 border-top-0 btn-white nav-item nav-link dropdown-toggle" type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false">
                                    Account
                                </button>
                                <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="dropdownMenuButton1">
                                    {% if not user.is_authenticated %}
                                        <li><a class="dropdown-item" href="{% url 'accounts:log_in' %}">Log in</a></li>
                                        <li><a class="dropdown-item" href="{% url 'accounts:sign_up' %}">Sign up</a></li>
                                    {% endif %}
                                    {% if user.is_authenticated %}
                                        <li><a class="dropdown-item" href="{% url 'accounts:log_out' %}">Sign out</a></li>
                                        <li><a class="dropdown-item" href="{% url 'accounts:change_password' %}">Password</a></li>
                                        <li><a class="dropdown-item" href="{% url 'accounts:change_profile' %}">Profile</a></li>
                                    {% endif %}
                                </ul>
                            </div>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
        {% block content %}{% endblock content %}
        
        <!-- Footer-->
        {% if active != 'Lucky' %}
        <section class="contact-section bg-black">
            <div class="container">
                <div class="social d-flex justify-content-center">
                    <a class="mx-2" href="#!"><i class="fab fa-twitter"></i></a>
                    <a class="mx-2" href="#!"><i class="fab fa-facebook-f"></i></a>
                    <a class="mx-2" href="#!"><i class="fab fa-github"></i></a>
                </div>
            </div>
        </section>
        <footer class="footer bg-black small text-center text-white-50"><div class="container px-4 px-lg-5">Copyright &copy; Brush &#38; Lens 2023</div></footer>
        {% endif %}
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- for contact form -->
        <script src="https://cdn.startbootstrap.com/sb-forms-latest.js"></script>
    </body>
</html>

brushandlens/root/templates/root/gallery.html
<!doctype html>

<html lang="en">

{% extends "root/base.html" %}
{% block header %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="../static/root/css/gallery.css">
{% endblock %}

{% block content %}
    <div class="body_wrapper">        
        <section class="breadcrumb_area_two breadcrumb_area_three parallaxie" data-background="img/bg.jpg" style="background: url(../static/root/images/cases_banner.jpg) no-repeat;">
            <div class="overlay"></div>
            <div class="container">
                <div class="breadcrumb_content text-center">
                    <h1>Gallery Studio</h1>
                    <p>Have a look around</p>
                </div>
            </div>
        </section>

        <section class="portfolio_area sec_pad">                
            <ul class="list-unstyled gallery_filter gallery_filter_two">
                    <li class="active" data-filter="*">All Artists</li>
                    <li data-filter=".design">Theme</li>
                </ul>
            <div id="cards" class="container">

                <div class="row gallery_inner_four" id="gallery">
                </div>
            </div>
        </section>
    </div>
    <script src="../static/root/js/galleryview.js"></script>
    <script>

        $(() => {
            const goatViewer = new GalleryViewer(1, 6);
            goatViewer.load();
        });
    </script>
    <script src="../static/root/js/parallaxie.js"></script>
    <script src="../static/root/js/imagesloaded.pkgd.min.js"></script>
    <script src="../static/root/js/isotope-min.js"></script>
    <script src="../static/root/js/custom.js"></script>

{% endblock content %}

brushandlens/root/templates/root/index.html
{% extends "root/base.html" %}

{% block header %}

{% endblock header %}

{% block content %}
<header class="masthead">
    <div class="container px-4 px-lg-5 d-flex h-100 align-items-center justify-content-center">
        <div class="d-flex justify-content-center">
            <div class="text-center ">
                <h1 class="mx-auto my-0 text-uppercase">Brush &#38; Lens</h1>
                <h2 class="text-white mx-auto mt-4 mb-4">Featured Art of the Week!</h2>
                <a class="btn btn-outline-light" href="/preview?img_id={{image.pk}}">Buy Now></a>
                <a class="btn btn-outline-light" href="/artistworks?id={{artist.pk}}">View Artist></a>
            </div>
        </div>
    </div>
</header>

<!-- Featured Artist-->
<section class="projects-section bg-light" id="projects">
    <div class="container px-4 px-lg-5">
        <div class="row gx-0 mb-5 mb-lg-0 justify-content-center">
            <div class="col-lg-6"><img class="img-fluid" src="../static/root/images/cat-7498364_1280.jpg" alt="..." /></div>
            <div class="col-lg-6">
                <div class="bg-black text-center h-100 project">
                    <div class="d-flex h-100">
                        <div class="project-text w-100 my-auto text-center text-lg-left">
                            <h4 class="text-white">Featured Artists</h4>
                            <p class="mb-0 text-white-50 mb-2">{{artist.name}}</p>
                            <p class="mb-0 text-white-50 mb-4">{{artist.description}}</p>
                            <a class="btn btn-outline-light" href="/artistworks?id=1">View ></a>
                            <hr class="d-none d-lg-block mb-0 ms-0" />
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="row gx-0 justify-content-center">
            <div class="col-lg-6"><img class="img-fluid" src="../static/root/images/bg-masthead.jpg" alt="..." /></div>
            <div class="col-lg-6 order-lg-first">
                <div class="bg-black text-center h-100 project">
                    <div class="d-flex h-100">
                        <div class="project-text w-100 my-auto text-center text-lg-right">
                            <h4 class="text-white">Featured Artists</h4>
                            <p class="mb-0 text-white-50 mb-2">Ansel Adams</p>
                            <p class="mb-0 text-white-50 mb-4">American photographer and environmentalist</p>
                            <a class="btn btn-outline-light" href="/artistworks?id=3">View ></a>
                            <hr class="d-none d-lg-block mb-0 me-0" />
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

<!-- Contact-->
<section class="contact-section bg-black">
    <div class="container px-4 px-lg-5">
        <div class="col-md-10 col-lg-8 mx-auto text-center">
            <h2 class="text-white mb-5">Contact US!</h2>
        </div>
        <div class="row gx-4 gx-lg-5">
            <div class="col-md-4 mb-3 mb-md-0">
                <div class="card py-4 h-100">
                    <div class="card-body text-center">
                        <i class="fas fa-map-marked-alt text-primary mb-2"></i>
                        <h4 class="text-uppercase m-0">Address</h4>
                        <hr class="my-4 mx-auto" />
                        <div class="small text-black-50">3675, Market Street, Philedelphia, PA</div>
                    </div>
                </div>
            </div>
            <div class="col-md-4 mb-3 mb-md-0">
                <div class="card py-4 h-100">
                    <div class="card-body text-center">
                        <i class="fas fa-envelope text-primary mb-2"></i>
                        <h4 class="text-uppercase m-0">Email</h4>
                        <hr class="my-4 mx-auto" />
                        <div class="small text-black-50"><a href="#!">hello@drexel.edu</a></div>
                    </div>
                </div>
            </div>
            <div class="col-md-4 mb-3 mb-md-0">
                <div class="card py-4 h-100">
                    <div class="card-body text-center">
                        <i class="fas fa-mobile-alt text-primary mb-2"></i>
                        <h4 class="text-uppercase m-0">Phone</h4>
                        <hr class="my-4 mx-auto" />
                        <div class="small text-black-50">+1 (267) 752-0353</div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

{% load static %}
<script src="{% static 'root/js/scripts.js' %}"></script>
{% endblock content %}